-- Arquivo de apoio, caso você queira criar tabelas como as aqui criadas para a API funcionar.
-- Você precisa executar os comandos no banco de dados para criar as tabelas,
-- ter este arquivo aqui não significa que a tabela em seu BD estará como abaixo!

/*
comandos para mysql server
*/

create database pinguim;

use pinguim;

create table usuario(
idUsuario int primary key auto_increment,
Nickname varchar(45),
Email varchar(45),
Senha varchar(45)
);

create table quiz(
idQuiz int primary key auto_increment,
titulo varchar(45),
descricao varchar(100)
);

insert into quiz (titulo, descricao) values
('Explorador da Ilha – O Grande Desafio', 'Descubra se conhece a ilha respondendo este quiz cheio de lugares, histórias e segredos curiosos!'),
('Heróis da Ilha – Quiz dos Personagens CP', 'Mostre que realmente conhece os personagens mais icônicos da ilha neste quiz especial e divertido!'),
('Missões da EPF – Desafio de Conhecimento"', 'Prove que é um agente de elite da EPF respondendo perguntas sobre missões, operações e segredos!'),
('Descubra Sua Personalidade como Agente da EPF', 'Descubra seu tipo de agente da EPF respondendo a este quiz rápido que revela seu perfil especial'),
('Descubra qual Puffle combina melhor com você!', 'Responda ao quiz e descubra qual Puffle combina melhor com você de acordo com sua personalidade!');

select* from quiz;


create table resultado_quiz(
	idResultado int primary key auto_increment,
    idUsuario int,
    idQuiz int,
    pontuacao int,
    foreign key (idUsuario) references usuario(idUsuario),
    foreign key (idQuiz) references quiz(idQuiz)
);

create table pergunta(
idPergunta int primary key auto_increment,
descricao varchar(100) not null,
FK_quiz int not null,
foreign key (FK_quiz) references quiz (idQuiz)
);

insert into pergunta (descricao, FK_quiz) values 
('Qual é o nome da montanha onde os pinguins fazem snowboard?', 16),
('Onde fica localizada a Pizzaria do Club Penguin?', 16),
('Qual é o nome do vulcão onde os Ninjas de Fogo treinam?', 16),
('Quem é o inventor famoso da ilha?', 16),
('Qual é o pet mais famoso e querido da ilha?', 16),
('Qual mini-jogo do Café envolvia bater em sacos de grãos?', 16),
('Quem é o líder dos ninjas no Dojo?', 16),
('Onde fica o famoso Iceberg?', 16),
('Qual é o jornal oficial da ilha?', 16),
('Quem é o principal vilão da ilha?', 16),
('Quem é o famoso cientista da ilha conhecido por suas invenções?',17),
('Qual personagem é o capitão pirata dono do navio Migrator?', 17),
('Quem é o mestre do Card-Jitsu e treinador de ninjas?', 17),
('Qual personagem é DJ, dançarina e estrela da Casa Noturna?', 17),
('Quem é a editora-chefe do Club Penguin Times e líder do EPF?', 17),
('Qual é o vilão mais famoso da ilha e inimigo dos pinguins?', 17),
('Qual agente secreto é conhecido por ser atrapalhado e engraçado?', 17),
('Qual pinguim é mestre em disfarces e furtividade?', 17),
('Quem é o guitarrista principal da Penguin Band?', 17),
('Quem é o agente conhecido por usar uma mochila a jato?', 17),
('Quem foi o responsável por destruir o antigo QG da PSA?', 18),
('Qual foi a primeira operação oficial da EPF?', 18),
('Qual agente é especialista em furtividade dentro da EPF?', 18),
('Em qual operação Herbert tenta mergulhar a ilha em escuridão permanente?', 18),
('Qual operação investigou o desaparecimento misterioso de vários puffles?', 18),
('Quem desenvolve as invenções usadas pelos agentes da EPF?', 18),
('Qual operação envolve recuperar o molho de pimenta roubado?', 18),
('Qual é o nome do urso polar que constantemente ameaça a EPF?', 18),
('Qual agente é conhecido por causar confusões, mas ainda assim ajudar?', 18),
('Qual operação lidou com um ataque massivo que desligou a energia da ilha?', 18),
('Se você chegasse na ilha agora, o que faria primeiro?', 19),
('Qual ambiente mais combina com você?', 19),
('Qual dessas qualidades mais te descreve?', 19),
('Em uma situação inesperada, você...', 19),
('O que mais te motiva?', 19),
('Qual desses papéis você assumiria em um grupo?', 19),
('Escolha um passatempo:', 19),
('Se um amigo estivesse em perigo, você…', 19),
('Qual dessas comidas escolheria?', 19),
('Como você se sente em relação a desafios?', 19),
('Qual dessas atividades você mais gosta', 20),
('Qual ambiente combina mais com você?', 20),
('Qual dessas qualidades te define melhor?', 20),
('Se algo inesperado acontecer...', 20),
('O que te motiva?', 20);

select * from pergunta;

create table resposta(
idResposta int auto_increment,
idPergunta int,
foreign key (idPergunta) references pergunta(idPergunta),
primary key (idResposta, idPergunta),
opcao char(1),
descricao varchar(100),
validacao TINYINT
);

INSERT INTO resposta (idPergunta, opcao, descricao, validacao) VALUES
(46, 'A', 'Pico Gelado', 0),
(46, 'B', 'Montanha Nevada', 1),
(46, 'C', 'Morro Congelado', 0),
(46, 'D', 'Ice Hill', 0),
(47, 'A', 'No Forte Nevado', 0),
(47, 'B', 'No Centro (Town)', 0),
(47, 'C', 'Na Plazas', 1),
(47, 'D', 'Na Praia', 0),
(48, 'A', 'Montanha Flamejante', 0),
(48, 'B', 'Vulcão do Dojo', 1),
(48, 'C', 'Pico do Fogo', 0),
(48, 'D', 'Caverna Vulcânica', 0),
(49, 'A', 'Rookie', 0),
(49, 'B', 'Sensei', 0),
(49, 'C', 'Gary', 1),
(49, 'D', 'Jet Pack Guy', 0),
(50, 'A', 'Puffles', 1),
(50, 'B', 'Waddles', 0),
(50, 'C', 'Snowpets', 0),
(50, 'D', 'Ice Pups', 0),
(51, 'A', 'Ice Fishing', 0),
(51, 'B', 'Bean Counters', 1),
(51, 'C', 'Smoothie Smash', 0),
(51, 'D', 'Sled Racing', 0),
(52, 'A', 'Herbert', 0),
(52, 'B', 'Sensei', 1),
(52, 'C', 'Gariwald', 0),
(52, 'D', 'Tia Arctic', 0),
(53, 'A', 'Perto da Mina', 0),
(53, 'B', 'Em área isolada no mapa', 1),
(53, 'C', 'Ao lado da Pizzaria', 0),
(53, 'D', 'No subsolo', 0),
(54, 'A', 'Penguin Times', 0),
(54, 'B', 'Ilha News', 0),
(54, 'C', 'The EPF Report', 0),
(54, 'D', 'Club Penguin News', 1),
(55, 'A', 'Klutzy', 0),
(55, 'B', 'Herbert P. Bear', 1),
(55, 'C', 'Protobot', 0),
(55, 'D', 'DJ Maxx', 0),
(56, 'A', 'Rockhopper', 0),
(56, 'B', 'Gary', 1),
(56, 'C', 'Sensei', 0),
(56, 'D', 'Rookie', 0),
(57, 'A', 'Gary', 0),
(57, 'B', 'Jet Pack Guy', 0),
(57, 'C', 'Rockhopper', 1),
(57, 'D', 'Franky', 0),
(58, 'A', 'Sensei', 1),
(58, 'B', 'Cadence', 0),
(58, 'C', 'Gary', 0),
(58, 'D', 'Dot', 0),
(59, 'A', 'Tia Arctic', 0),
(59, 'B', 'Cadence', 1),
(59, 'C', 'Dot', 0),
(59, 'D', 'Penny', 0),
(60, 'A', 'Cadence', 0),
(60, 'B', 'Aunt Arctic', 1),
(60, 'C', 'Dot', 0),
(60, 'D', 'Sensei', 0),
(61, 'A', 'Rookie', 0),
(61, 'B', 'Herbert P. Bear', 1),
(61, 'C', 'Protobot', 0),
(61, 'D', 'Gariwald', 0),
(62, 'A', 'Jet Pack Guy', 0),
(62, 'B', 'Franky', 0),
(62, 'C', 'Rookie', 1),
(62, 'D', 'Rockhopper', 0),
(63, 'A', 'Dot', 1),
(63, 'B', 'Sensei', 0),
(63, 'C', 'Franky', 0),
(63, 'D', 'Tia Arctic', 0),
(64, 'A', 'Stompin’ Bob', 1),
(64, 'B', 'G Billy', 0),
(64, 'C', 'Franky', 0),
(64, 'D', 'Cadence', 0),
(65, 'A', 'Jet Pack Guy', 1),
(65, 'B', 'Rookie', 0),
(65, 'C', 'Gary', 0),
(65, 'D', 'Rockhopper', 0),
(66, 'A', 'Gary', 0),
(66, 'B', 'Herbert', 1),
(66, 'C', 'Rookie', 0),
(66, 'D', 'Klutzy', 0),
(67, 'A', 'Operação Blackout', 0),
(67, 'B', 'Operação Submarino', 0),
(67, 'C', 'Operação Hot Sauce', 1),
(67, 'D', 'Operação Apagão', 0),
(68, 'A', 'Jet Pack Guy', 0),
(68, 'B', 'Rookie', 0),
(68, 'C', 'Dot', 1),
(68, 'D', 'Gary', 0),
(69, 'A', 'Operação Blackout', 1),
(69, 'B', 'Operação Hot Sauce', 0),
(69, 'C', 'Operação Vulcão', 0),
(69, 'D', 'Operação Fóton', 0),
(70, 'A', 'Operação Puffle', 1),
(70, 'B', 'Operação Resgate', 0),
(70, 'C', 'Operação Neve', 0),
(70, 'D', 'Operação Patinete', 0),
(71, 'A', 'Rookie', 0),
(71, 'B', 'Gary', 1),
(71, 'C', 'Sensei', 0),
(71, 'D', 'Tia Arctic', 0),
(72, 'A', 'Operação Picante', 0),
(72, 'B', 'Operação Hot Sauce', 1),
(72, 'C', 'Operação Fogo', 0),
(72, 'D', 'Operação Spice', 0),
(73, 'A', 'Rufus', 0),
(73, 'B', 'Herbert P. Bear', 1),
(73, 'C', 'Fluffy', 0),
(73, 'D', 'Gariwald', 0),
(74, 'A', 'Dot', 0),
(74, 'B', 'Gary', 0),
(74, 'C', 'Rookie', 1),
(74, 'D', 'Jet Pack Guy', 0),
(75, 'A', 'Operação Apagão', 0),
(75, 'B', 'Operação Blackout', 1),
(75, 'C', 'Operação Luz', 0),
(75, 'D', 'Operação Neve Profunda', 0),
(76, 'A', 'Exploraria todos os cantos da ilha!', 0),
(76, 'B', 'Começaria a inventar algo novo.', 0),
(76, 'C', 'Iria direto ao Dojo treinar.', 0),
(76, 'D', 'Visitava amigos para conversar.', 0),
(77, 'A', 'Um navio cheio de mistérios.', 0),
(77, 'B', 'Um laboratório cheio de ferramentas.', 0),
(77, 'C', 'Um local silencioso onde posso treinar.', 0),
(77, 'D', 'Uma redação tranquila com bons livros.', 0),
(78, 'A', 'Corajoso', 0),
(78, 'B', 'Inventivo', 0),
(78, 'C', 'Disciplinado', 0),
(78, 'D', 'Observador', 0),
(79, 'A', 'Age rápido, sem pensar muito.', 0),
(79, 'B', 'Cria uma solução alternativa e criativa.', 0),
(79, 'C', 'Mantém o foco e lidera o grupo.', 0),
(79, 'D', 'Mantém a calma e avalia tudo com cuidado.', 0),
(80, 'A', 'Descobrir algo novo todos os dias.', 0),
(80, 'B', 'Criar coisas que ninguém pensou.', 0),
(80, 'C', 'Treinar e melhorar sempre.', 0),
(80, 'D', 'Ajudar os outros com paciência.', 0),
(81, 'A', 'Explorador', 0),
(81, 'B', 'Inventor', 0),
(81, 'C', 'Mestre estrategista', 0),
(81, 'D', 'Conselheiro', 0),
(82, 'A', 'Viajar', 0),
(82, 'B', 'Montar experimentos', 0),
(82, 'C', 'Meditação e treino', 0),
(82, 'D', 'Escrever e ler', 0),
(83, 'A', 'Correria para salvá-lo!', 0),
(83, 'B', 'Criaria um plano rápido para tirá-lo dali.', 0),
(83, 'C', 'Guiaria todos para agir em equipe.', 0),
(83, 'D', 'Tentaria mantê-lo calmo enquanto busca ajuda.', 0),
(84, 'A', 'Algo diferente e ousado.', 0),
(84, 'B', 'Algo que eu mesmo inventasse.', 0),
(84, 'C', 'Algo simples e equilibrado.', 0),
(84, 'D', 'Algo clássico e reconfortante.', 0),
(85, 'A', 'Adoro! Me jogo sem medo.', 0),
(85, 'B', 'Encaro criando soluções criativas.', 0),
(85, 'C', 'Uso disciplina e foco.', 0),
(85, 'D', 'Penso com calma e estratégia.', 0),
(86, 'A', 'Explorar e correr por aí!', 0),
(86, 'B', 'Criar coisas novas e mexer com ferramentas.', 0),
(86, 'C', 'Treinar e se dedicar com disciplina.', 0),
(86, 'D', 'Relaxar e observar tudo com calma.', 0),
(87, 'A', 'Lugares cheios de energia!', 0),
(87, 'B', 'Ateliês, oficinas e lugares criativos.', 0),
(87, 'C', 'Ambientes silenciosos e focados.', 0),
(87, 'D', 'Locais tranquilos e aconchegantes.', 0),
(88, 'A', 'Aventureiro', 0),
(88, 'B', 'Artístico', 0),
(88, 'C', 'Intenso', 0),
(88, 'D', 'Calmo', 0),
(89, 'A', 'Pulo na ação imediatamente!', 0),
(89, 'B', 'Penso em algo criativo para resolver.', 0),
(89, 'C', 'Fico sério e enfrento de forma direta.', 0),
(89, 'D', 'Respiro fundo e observo antes de agir.', 0),
(90, 'A', 'Emoção e movimento!', 0),
(90, 'B', 'Criatividade e expressão.', 0),
(90, 'C', 'Foco total e intensidade.', 0),
(90, 'D', 'Conforto e paz.', 0);

select * from resposta;


create table mensagem (
	id int primary key auto_increment,
	titulo varchar(100),
	descricao varchar(150),
	fk_usuario INT,
	foreign key (fk_usuario) references usuario(idUsuario)
);